pipeline {
    agent any

    environment {
        ECR_REPO = "326991552997.dkr.ecr.ap-northeast-2.amazonaws.com/test-cicd"
        AWS_CREDENTIALS = "jenkins_deploy_user_credentials"
        NAME = "test"

        ECS_CLUSTER_NAME = "test-cluster"
        ECS_SERVICE_NAME = "test-service"
    }

    stages {
        stage("========== Test the project ==========") {
            steps {
                dir("${env.WORKSPACE}") {
                    sh 'chmod 755 ./gradlew'
                    sh './gradlew clean test'
                }
            }
        }


        stage("========== Build the project ==========") {
            steps {
                dir("${env.WORKSPACE}") {
                    sh './gradlew clean build'
                }
            }
        }

        stage("========== Build Docker Image ==========") {
            steps {
                dir("${env.WORKSPACE}") {
                    sh 'docker build -t ${NAME} .'
                    sh 'docker tag ${NAME}:latest ${ECR_REPO}:latest'
                }
            }
        }

        stage("========== ECR Upload ==========") {
            steps {
                script {
                    try {
                        withAWS(credentials: "${AWS_CREDENTIALS}", role: 'arn:aws:iam::326991552997:role/jenkins_deploy_role', roleAccount: "326991552997", externalId: "18k7102dy@gmail.com") {
                            sh "aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${ECR_REPO}"
                            sh "docker push ${ECR_REPO}:latest"
                        }
                    }catch(error) {
                        print(error)
                        currentBuild.result = 'FAILURE'
                    }
                }
            }

            post {
                success {
                    echo "The ECR Upload stage is done successfully."
                }
                failure {
                    echo "The ECR Upload stage is fail."
                }
            }
        }

        stage("========== Deploy to Fargate ==========") {
            steps {
                script {
                    try {
                        withAWS(credentials: "${AWS_CREDENTIALS}", role: 'arn:aws:iam::326991552997:role/jenkins_deploy_role', roleAccount: "326991552997", externalId: "18k7102dy@gmail.com") {
                            sh "aws ecs update-service --region ap-northeast-2 --cluster ${ECS_CLUSTER_NAME} --service ${ECS_SERVICE_NAME} --force-new-deployment"
                        }
                    }catch(error) {
                        print(error)
                        echo 'Remove Deploy Files'
                        sh "sudo rm -rf /var/lib/jenkins/workspace/${env.JOB_NAME}/*"
                        currentBuild.result = 'FAILURE'
                    }
                }
            }

            post {
                success {
                    echo "The Fargate deploy stage is done successfully."
                }
                failure {
                    echo "The Fargate deploy stage is fail."
                }
            }
        }
    }

    post {
        success {
            slackSend(
                channel: "#server-build-history",
                color: "good",
                message: "[Successful] Job:${env.JOB_NAME}, Build num:#${env.BUILD_NUMBER} (<${env.RUN_DISPLAY_URL}|open job detail>)"
            )
        }

        failure {
            slackSend(
                channel: "#server-build-history",
                color: "danger",
                message: "[Failed] Job:${env.JOB_NAME}, Build num:#${env.BUILD_NUMBER} @channel (<${env.RUN_DISPLAY_URL}|open job detail>)"
            )
        }
    }
}